version: 2



build:
  os: ubuntu-20.04
  tools:
    python:
      version: 3.10
  jobs:
    pre_install:
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install poetry
      - poetry install --with docs

        

sphinx:
  configuration: docs/conf.py