version: 2



build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - python -m venv .venv
    - /bin/bash source .venv/bin/activate
    - poetry install --with docs
    - make build-docs
