version: 2



build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - python -m venv .venv
    - chmod +x .venv/bin/activate
    - source .venv/bin/activate
    - pip install poetry
    - poetry install --with docs
    - make build-docs
