name: Package Testing
on:
    - push

jobs:
    TestPackage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Set up Poetry
              run: |
                  pip install poetry
            - name: Install test dependencies
              run: |
                  poetry install --with test
            - name: Check formatting and PEP8
              run: |
                    poetry run isort --check-only src/tatm tests
                    poetry run black --check src/tatm tests
                    poetry run flake8 src/tatm tests
            - name: Run tests
              run: |
                  poetry run pytest --cov=src/tatm --cov-fail-under=85 tests

