name: Create Release
on: workflow_dispatch

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Get dev SHA
              id: get_sha
              run: echo "dev-sha=$(git rev-parse dev)" >> $GITHUB_OUTPUT
            - name: create-branch
              uses: peterjgrainger/action-create-branch@v3.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                 branch: release
                 sha: ${{ steps.get_sha.outputs.dev-sha }}