name: release-prep
on:
  pull_request:
    branches:
      - main
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    release-check:
        if: github.event.action == 'labeled' && (github.head_ref == 'dev' || contains(github.head_ref, 'hotfix'))
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Post bumpr status comment
          id: bumpr
          uses: haya14busa/action-bumpr@v1
        - name: Set up Python
          id: setup_python
          uses: actions/setup-python@v3
          with:
              python-version: "3.10"
        - name: Set up Poetry
          run: |
            pip install poetry
        - name: bump package version
          run: |
              new_version=`echo ${{ steps.bumpr.outputs.next_version }} | sed 's/^v//'`
              branch_version=`poetry version | awk '{print $2}'`
              echo "Current version: $branch_version"
              echo "New version: $new_version"
              if [ "$branch_version" != "$new_version" ]; then
                  echo "Version is not up to date"
                  exit 1
              else
                  echo "Version is already up to date"
              fi
        - name: Hotfix PR to dev
          if: contains(github.head_ref, 'hotfix')
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              gh pr create --base dev --head ${{ github.head_ref }} --title "Hotfix ${{ steps.bumpr.outputs.next_version }}" --body "Hotfix ${{ steps.bumpr.outputs.next_version }}"
